version: '3'
services:
  dc-portfolio-fe:
    image: dc-portfolio-fe
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - dc-portfolio-mern
    volumes:
      - ./client:/usr/src/app
  dc-portfolio-be:
    image: dc-portfolio-be
    ports:
      - "5000:5000"
    # environment:
    #   - MONGO_URI=mongodb://dc-portfolio-db:27017/portfolio-db
    #   - PORT=5000
    networks:
      - dc-portfolio-mern
    depends_on:
      - dc-portfolio-db
    volumes:
      - ./server:/usr/src/app
  dc-portfolio-db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - dc-portfolio-mern
    volumes:
      - mongo-data:/data/db
networks:
  dc-portfolio-mern:
    driver: bridge
volumes:
  mongo-data:
    driver: local