version: '3'
services:
  dc-portfolio-fe:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - dc-portfolio-mern
    volumes:
      - dc-client-data:/usr/src/app
    environment:
      - API_BASE=http://dc-portfolio-be:5000/api
    depends_on:
      - dc-portfolio-be
  dc-portfolio-be:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - dc-portfolio-mern
    depends_on:
      - dc-portfolio-db
    volumes:
      - dc-backend-data:/usr/src/app
  dc-portfolio-db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - dc-portfolio-mern
    volumes:
      - mongo-data:/data/db
networks:
  dc-portfolio-mern:
    driver: bridge
volumes:
  dc-backend-data:
  dc-client-data:
  mongo-data:
    driver: local
